project:
  type: website
  output-dir: docs

website:
  title: "CHI-FILES"
  open-graph: true # https:quarto.org.docs/websites/website-tools.html#open-graph
  page-footer: "Made with ğŸ’— and â˜•ï¸ and Quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chichacha
  sidebar:
    contents: auto

format:
  html:
    theme:  # https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/html/bootstrap/themes
      light: flatly
      dark: darkly
    css: styles.css



