project:
  type: website
  output-dir: docs
output:
  rss: 
    path: "r.xml"
    filter: ".categories == 'r'"
  
  
author: "Chisato"
date-format: "long"  # Options: "short", "long", "relative"


website:
  title: "CHI(Ï‡)-Files"
  site-url: "https://chichacha.github.io/chi-files"
  open-graph: false # https:quarto.org.docs/websites/website-tools.html#open-graph
  page-footer: "Made with ğŸ’—  Powered by ğŸª„ [Quarto](https://quarto.org/) âœ¨ and fueled by â˜•ï¸ ğŸ and procrastination"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chichacha
      - icon: rss
        href: https://www.r-bloggers.com

format:
  html:
    theme:  # https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/html/bootstrap/themes
      #dark: darkly
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    include-in-header: google_analytics.html
    
page-layout: full

execute:
  echo: false       # Hide code chunks by default
  warning: false    # Suppress warnings
  message: false    # Suppress messages






