project:
  type: website
  output-dir: docs
  
author: "Chisato"
date-format: "long"  # Options: "short", "long", "relative"


website:
  title: "CHI(œá)-Files"
  site-url: "https://chichacha.github.io/chi-files"
  open-graph: false # https:quarto.org.docs/websites/website-tools.html#open-graph
  page-footer: "Made with üíó and ‚òïÔ∏è and Quarto"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chichacha

format:
  html:
    theme:  # https://github.com/quarto-dev/quarto-cli/tree/main/src/resources/formats/html/bootstrap/themes
      #dark: darkly
      light: flatly
    css: styles.css
    toc: true
    toc-depth: 4
    include-arter-body: |
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-4EK13JXE55"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'G-4EK13JXE55');
      </script>
    
page-layout: full

execute:
  echo: false       # Hide code chunks by default
  warning: false    # Suppress warnings
  message: false    # Suppress messages






